# Generated by Django 5.2.6 on 2026-06-08 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('knowledge_base', '0005_knowledgecategory_knowledgedocument_categories'),
        ('tickets', '0003_ticket_category_ticket_escalated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='tickets.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_active_tickets',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AgentExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_count', models.IntegerField(default=0)),
                ('expertise_level', models.CharField(default='Low', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.knowledgecategory')),
            ],
            options={
                'unique_together': {('agent', 'category')},
            },
        ),
    ]
