# Generated by Django 5.2.6 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_expertise_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_ticket_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sentiment_handling_score',
            field=models.FloatField(default=0.0),
        ),
    ]
