# Generated by Django 5.2.6 on 2026-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgedocument_processed_at_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
