# Generated by Django 5.2.6 on 2026-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_documentchunk_embedding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='BAAI/bge-base-en-v1.5 embedding vector', null=True),
        ),
    ]
