# Generated by Django 5.2.6 on 2026-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_documentchunk_embedding_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents', to='knowledge_base.knowledgecategory'),
        ),
    ]
