# Generated by Django 5.2.6 on 2026-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_category_ticket_escalated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('hr', 'HR'), ('facilities', 'Facilities'), ('finance', 'Finance'), ('admin', 'Administration'), ('other', 'Other')], default='other', help_text='Type of support request', max_length=50),
        ),
    ]
