# Generated by Django 5.2.6 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority_reason',
            field=models.TextField(blank=True, help_text='Reason for AI priority recommendation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Intelligent calculated priority score'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='AI detected sentiment confidence/score'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_risk_level',
            field=models.CharField(default='low', help_text='Predicted SLA breach risk level', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_risk_score',
            field=models.FloatField(default=0.0, help_text='Predicted SLA breach risk score'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(blank=True, default='Neutral', help_text='AI detected sentiment', max_length=50),
        ),
    ]
